# Generated by Django 4.2.1 on 2023-05-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_slidernews'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidernews',
            name='news_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slidernews',
            name='news_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
