# Generated by Django 4.2.1 on 2023-05-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_slidernews_news_desc_slidernews_news_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='latestNews/')),
                ('timestamp', models.TimeField(auto_now=True)),
            ],
        ),
    ]
