# Generated by Django 4.2.1 on 2023-05-24 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_latestnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='articles/')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('author_name', models.CharField(max_length=30)),
                ('author_image', models.ImageField(upload_to='authorImages/')),
                ('is_draft', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.category')),
            ],
        ),
    ]
