# Generated by Django 4.2.1 on 2023-05-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=200)),
                ('video_type', models.CharField(max_length=30)),
            ],
        ),
    ]
