# Generated by Django 4.2.1 on 2023-05-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_video_video_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='latestVideos/')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
    ]
