# Generated by Django 4.2.1 on 2023-05-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_latestvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestvideo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
