# Generated by Django 4.2.1 on 2023-05-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_sportlight_is_display_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportlight',
            name='is_celebrity_news',
            field=models.BooleanField(default=False),
        ),
    ]
