# Generated by Django 4.2.1 on 2023-05-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_sportlight_is_celebrity_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='website.tag'),
        ),
        migrations.AddField(
            model_name='sportlight',
            name='tags',
            field=models.ManyToManyField(to='website.tag'),
        ),
    ]
