# Generated by Django 4.2.1 on 2023-06-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('facebook_link', models.CharField(max_length=250)),
                ('twitter_link', models.CharField(max_length=250)),
                ('youtube_link', models.CharField(max_length=250)),
            ],
        ),
    ]
