# Generated by Django 4.2.1 on 2023-06-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_websitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='file_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
