# Generated by Django 4.2.1 on 2023-06-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_art'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtLatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='latest_news/')),
                ('title', models.CharField(max_length=100)),
                ('timeStamp', models.DateTimeField(auto_now=True)),
                ('is_trending_news', models.BooleanField(default=False)),
            ],
        ),
    ]
