# Generated by Django 4.2.1 on 2023-06-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_artlatestnews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportlight',
            old_name='image',
            new_name='banner',
        ),
    ]
