# Generated by Django 4.2.1 on 2023-06-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_rename_image_sportlight_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latestnews',
            old_name='image',
            new_name='banner',
        ),
    ]
