# Generated by Django 4.2.1 on 2023-06-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_rename_image_latestnews_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportlight',
            old_name='timestamp',
            new_name='timeStamp',
        ),
    ]
