# Generated by Django 4.2.1 on 2023-06-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_rename_timestamp_sportlight_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latestnews',
            old_name='timestamp',
            new_name='timeStamp',
        ),
    ]
