# Generated by Django 4.2.1 on 2023-09-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_rename_timestamp_latestnews_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='Magazine_image/')),
                ('title', models.CharField(max_length=100)),
                ('timeStamp', models.TimeField(auto_now=True)),
                ('description', models.TextField()),
                ('is_trending_news', models.BooleanField(default=False)),
            ],
        ),
    ]
