# Generated by Django 4.2.1 on 2023-09-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_magazine'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='is_latest_news',
            field=models.BooleanField(default=False),
        ),
    ]
