# Generated by Django 4.2.1 on 2023-09-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_magazine_is_latest_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestnews',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
