# Generated by Django 4.2.1 on 2023-09-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_latestnews_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestvideo',
            name='video_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
