# Generated by Django 4.2.1 on 2023-09-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_article_author_facebook_article_author_instagram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author_instagram',
            new_name='author_twitter',
        ),
    ]
