# Generated by Django 4.2.1 on 2023-09-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_rename_author_instagram_article_author_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='copy_right',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
